language: node_js
node_js:
  - stable

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8



notifications:
  slack: codusmaximus:TfshAEu8LRkjOGkyZnOQq5ys
  webhooks: http://hyperperform.me:8080/hyperperform-system-1.0-SNAPSHOT/rs/TravisEvent

install:
  - npm config set spin false
  - npm install -g npm@3
  - npm install -g gulp
  - npm install -g bower

  - npm install

script:
  - gulp build
