language: java

env:
  global:
  - secure: ljImdd7PjxKxZkOhuqE9kRcFax1+mHYBOxYHwvrheUTIKdTujohPZx8R8spJAkL1leQSjxjfccbjHhxoYg3tbB0r+JRnllk28+i1iKPoR1tNDtwH9iUQDmNgl44vj7Q9KM1kxuuwHY4KuThWR+RfGfpwcnZbkaQMAbOO31m9u75NGWHX6Aam2loPKuD4nd/DUxhy83TYGLtiH9UMe0dY7b2XZHfsJLuM/Sp/j9UFHuQuRi+ZzLGNLSIiI2tmq3sViQU0UDJoinWg+vAVWkPZYCoh5dANW0O4gCiueQ2lIyEAch0CfZCxmIjR5kOxMIdeFnrpReKia7lGv4AGQDp7htNr6q667RF9SiQPYCPZRvmqXriyey7t3pa1JbdBByMa9oHJMqCCl/+e0695BRszkdwds1pCAJ/PIwT4QaYj4zNzIrT2EWnqsiTLGaLvX12/a4710bTVQFbmQ3HoAV1FP85IeZ/++gT1MxHk18Q1ISNUWGGIthtSbnzdHaIOxGSij0EKRmRI/Vfe+6aYDNAZhF3R1GQrVXS9HkG+RqAjO1d0k0aH+lTz/UQGf66TB+2zD4P7TLFTd/n+rtfashwsUBN8JFjAIVnxlLMWI+58kw/3iAO4UUcVUTEmxhDby4WQUbsK0U2acjB9FDqw5SquLSm+3bDmxEBWyVNPbXTvJJo=

script:
  - mvn test

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE hyperperform;' -U postgres
  - psql -d hyperperform -c 'CREATE TABLE public."GitPush" ( id integer NOT NULL, repository character varying(255), "timestamp" timestamp without time zone, username character varying(255), CONSTRAINT "GitPush_pkey" PRIMARY KEY (id) ); CREATE SEQUENCE public.hibernate_sequence INCREMENT 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1;' -U postgres

test:
  adapter: postgresql
  database: hyperperform

after_success:
  - ./deploy.sh
  
notifications:
  slack: codusmaximus:TfshAEu8LRkjOGkyZnOQq5ys